services:
  wordpress:
    container_name: wordpress
    hostname: wordpress
    image: inception-wordpress:latest
    build: wordpress
    env_file:
      - .env
    networks:
      - inception_net
    volumes:
      - wp_files:/var/www/html
    depends_on:
      - mariadb
  nginx:
    container_name: nginx
    hostname: nginx
    image: inception-nginx:latest
    build: nginx
    ports:
      - 443:443
    networks:
      - inception_net
    volumes:
      - wp_files:/var/www/html
    depends_on:
      - wordpress
  mariadb:
    container_name: mariadb
    hostname: mariadb
    env_file:
      - .env
    image: inception-mariadb:latest
    build: mariadb
    networks:
      - inception_net
    volumes:
      - db_files:/var/lib/mysql
  # BONUS
  redis:
    container_name: redis
    hostname: redis
    env_file:
      - .env
    image: inception-redis:latest
    build: ./bonus/redis
    networks:
      - inception_net
    volumes:
      - wp_files:/var/www/html

volumes:
  wp_files:
    name: wp_volume
    driver: local
    driver_opts:
      type: none
      device: ${BASE_PATH}/data/wordpress
      o: bind
  db_files:
    name: db_volume
    driver: local
    driver_opts:
      type: none
      device: ${BASE_PATH}/data/mariadb
      o: bind

networks:
  inception_net:
    driver: bridge
    name: inception_net
