services:
  wordpress:
    container_name: wordpress
    hostname: wordpress
    image: inception-wordpress:latest
    build: wordpress
    env_file:
      - .env
    networks:
      - inception_net
    volumes:
      - wp_files:/var/www/html
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    hostname: nginx
    image: inception-nginx:latest
    build: nginx
    ports:
      - 443:443
    networks:
      - inception_net
    volumes:
      - wp_files:/var/www/html
    depends_on:
      - wordpress
    restart: always

  mariadb:
    container_name: mariadb
    hostname: mariadb
    env_file:
      - .env
    image: inception-mariadb:latest
    build: mariadb
    networks:
      - inception_net
    volumes:
      - db_files:/var/lib/mysql
    restart: always

  # BONUS
  redis:
    container_name: redis
    hostname: redis
    env_file:
      - .env
    image: inception-redis:latest
    build: redis
    networks:
      - inception_net
    volumes:
      - wp_files:/var/www/html
    restart: always

  ftp:
    container_name: ftp
    hostname: ftp
    env_file:
      - .env
    image: inception-ftp:latest
    build: ftp
    ports:
      - 21:21
      - 30000-30020:30000-30020
    networks:
      - inception_net
    volumes:
      - wp_files:/var/www/html
    restart: always

  portainer:
    container_name: portainer
    hostname: portainer
    image: inception-portainer:latest
    build: portainer
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception_net
    restart: always

volumes:
  wp_files:
    name: wp_volume
    driver: local
    driver_opts:
      type: none
      device: ${BASE_PATH}/data/wordpress
      o: bind
  db_files:
    name: db_volume
    driver: local
    driver_opts:
      type: none
      device: ${BASE_PATH}/data/mariadb
      o: bind
  portainer_data:
    name: portainer_data
    driver: local

networks:
  inception_net:
    driver: bridge
    name: inception_net
  