#!/bin/bash

# Get the list of all stopped containers
containers=$(sudo docker ps -aq)

# Remove containers if there are any
if [ -n "$containers" ]; then
  sudo docker container rm -f $containers
else
  echo "No stopped containers to remove."
fi

# Get the list of all Docker images
images=$(sudo docker images -aq)

# Remove images if there are any
if [ -n "$images" ]; then
  sudo docker image rm -f $images
else
  echo "No Docker images to remove."
fi

docker-compose down --remove-orphans -v

volumes=$(sudo docker volume ls -q)
if [ -n "$volumes" ]; then
  sudo docker volume rm -f $volumes
else
  echo "No Docker volume to remove."
fi

